(in-package #:lispore.tests)

(deftest application-command-wires-clingon ()
  (let ((command (lispore.app::new-application-command)))
    (check (string= "lispore" (clingon:command-name command))
           "The application command has the wrong name.")
    (check (string= "0.1.0" (clingon:command-version command))
           "The application command has the wrong version.")
    (check (functionp (clingon:command-handler command))
           "The application command has no handler.")
    (check (null (clingon:command-sub-commands command))
           "The application command still exposes subcommands.")
    (check (string= "<new|get|set|del> <path> [value]"
                    (clingon:command-usage command))
           "The application command has the wrong operation usage.")))
